### ISSUE TITLE
Issues with data from literacy snapshot not matching data from results section

### ISSUE THREAD

**Issue by carolinehchristopher** [chalkclassroom/CoachingApp#585]
	Literacy snapshot doesn’t match data in results summary in foundational skills and in writing
	This seems to also depend on the activity type the user chooses
•	Could be delay in Big Query?
•	And some instances of no data showing up in actual results when there was some in the snapshot
•	For journal activity setting, no data in snapshot but data in summary
•	Book reading – whole group lesson, the data don’t show up
I've attached a file that explains the various issues (plus just some instances where the snapshot cuts off the labels under the graphs, but you know about those already).
[literacy_bugs Irene found 6.28.22.pdf](https://github.com/chalkclassroom/CoachingApp/files/9004148/literacy_bugs.Irene.found.6.28.22.pdf)

**Comment by areyn77463** [comment]
@carolinechristopher - I changed the functionality of the "Complete Observation" button to log the currently chosen options after the user chooses an activity. Now you don't have to wait for the "go to next observation" popup every minute if you are done early and the correct data shows up in both the summary and results page. However, in order to make multiple observations in the same session you will have to wait for the one minute timer to run down and choose "go to next observation." Is this correct? 

Also, I am a little confused with what you are asking to be done for everything under "Result- book reading section" in the pdf. The data shown on the results details page reflects only what was chosen in the most recent observation and the data in the trends section seems to show the sum of the current day's observations for each activity. Is this incorrect?

**Comment by carolinehchristopher** [comment]
@areyn77463 for the first question, the "Complete Observation" button completes the whole observation.  The goal of it isn't to move on to the next coding interval, but to stop the whole classroom visit.  We just wanted to make it so that if you are in the middle of one of the 1-minute intervals and want the whole observation to end (leave the classroom), you can complete the observation without having to wait until that 1-minute interval ends.  Does that make more sense?  Happy to jump on Zoom if that's helpful.

For the second question, I'll need to jump on the website and refresh my memory.  But I'll get back to you on that for sure!
Thanks for all of your work on this!

**Comment by carolinehchristopher** [comment]
p.s. as an example (for your first question), Math works the way I want it to as long as you've at least recorded data in one full interval.  The data don't show up in results for an interval during which you clicked a checklist item but didn't wait for the interval to be over before you clicked "Complete Observation".

Also, I just tested Literacy, and it seems to be working fine -- it recorded data appropriately regardless of what activity setting I chose.  Maybe we just close that issue.

**Comment by areyn77463** [comment]
@carolinehchristopher - Ok, I misunderstood the "No data in the summary, but there is data in the result section" issue in the pdf. I will revert the changes because how the Math button works now is how the Literacy button worked before. Thank you for clearing that up for me. I believe all of the issues experienced are due to the database which we are currently working to resolve.

**Comment by carolinehchristopher** [comment]
Thanks @areyn77463 !
