### ISSUE TITLE
Teachers created in Coach account don't show up in Leader Dashboard

### ISSUE THREAD

**Issue by carolinehchristopher** [chalkclassroom/CoachingApp#631]
When we attempt to access the list of teachers in the leader dashboard, the teachers that were created from a coach account do not show up.  They only show up in the coach account where they were created, when you go into the results section and select the teacher.

**Comment by areyn77463** [comment]
@carolinehchristopher Hello Dr. @ChaseChilders and I looked into this and found that the school entered needs to match a previously created site's name. For example, in the staging environment you would need to enter "Lake Taylor" as the school name when creating a teacher from the My Teachers page as a coach or admin for them to show up in the users page. Another way would be to create a site with the same school name you gave to the teacher; however, the add sites functionality in the users page is currently being worked on and is not working as intended. Should we change the form so that a dropdown of the sites available to the coach appear instead of entering a name manually?

**Comment by carolinehchristopher** [comment]
@areyn77463 I think that changing it so that a dropdown of available sites to the coach appears makes sense (and avoids the issue of the coach maybe putting a site's name in differently, resulting in it not showing up on the users page... Like typing "Lake Taylor Childcare Center" instead of just Lake Taylor).  But it would mean someone has to enter sites from the Leader Dashboard for them to populate as options for the coach if they're wanting to add a teacher.  Correct?

**Comment by areyn77463** [comment]
@carolinehchristopher Yes, that is correct.

**Comment by carolinehchristopher** [comment]
@areyn77463 Is there a way that a site could be added in both places separately (from coach account or from leader dashboard), and both would show up in users section of the dashboard?  Then if there is an inconsistent name, the person could use the transfer function to assign the teacher to the correctly named site?
If not, I think to avoid the issue of coaches entering a site name that isn't identical to what has been added (same site, but name mismatch), it would make sense to have the coach account include a dropdown for all sites that are available to the coach.

**Comment by areyn77463** [comment]
Creating sites from both places is a possibility; however, the action of creating a site should probably be reserved to those with higher authority. A dropdown field for **School** when a coach is creating a teacher will greatly reduce the possibility of errors in the form and multiple sites with misspelled names. Is changing the text field to a dropdown ok with you?

**Comment by areyn77463** [comment]
Also, have you reviewed my reply to the leaders dashboard being wonky issue?

**Comment by carolinehchristopher** [comment]
@areyn77463 yes, I think that makes sense (i.e., changing the text field to a dropdown as you indicated above).
I haven't reviewed your reply to the leaders dashboard issue, but I'll look at it now.  Sorry for slower response times -- it's been a busy day

**Comment by areyn77463** [comment]
@carolinehchristopher Absolutely no problem Ms. We will add this to the board and I am confident you will see the issue remedied in the upcoming deployment prior to the Thanksgiving holiday.
